pipeline:

  build:
    image: golang:alpine
    commands:
      - cd listener && GOARCH=amd64 GOOS=linux go build -o bin/listener . && ls -lah bin
      - cd ../notifier && GOARCH=amd64 GOOS=linux go build -o bin/notifier . && ls -lah bin
    when:
      event: 
        - push
        - pull_request

  sonar-scanner:
    image: quay.io/ukhomeofficedigital/sonar-scanner:v4.3.0
    when:
      event:
        - pull_request
      branch:
        - master
